## Base URL - Used primarily on share links
baseURL = '/'

## Directories
assetDir = '/source/assets'
archetypeDir = '/source/archetypes'
layoutDir = '/source/layouts'
staticDir = '/source/static' 
resourceDir = '/source'

## Disables
disableKinds = ['section'] 

## Disqus
disqusShortname = ''

## Inline Shortcodes
enableInlineShortcodes = true

## Taxonomies
[taxonomies]
	tag = 'tags'

## Permalinks
[permalinks]
	posts = '/:filename'

## Layout Parameters
[params]

	## Social Media Data
	title = 'D. Travis Lee'
	image = '/dtlee-apple-touch.png'
	
	## Copyright
	copyright = 'All Rights Reserved'
	author = 'D. Travis Lee'
	
	## Language
	lang = 'en-us'
	
	## RSS Limit - number of posts in RSS
	rss = 25
	
	## Pagination size
	paginate = 10
	
	## Taxonomy pagination size
	taxPaginate = 20
	
	## Summary length - length of summaries in RSS and metadata, in characters
	## Also applies to descriptions if they are set for a page
	sumLen = 150
	
	## Robots.TXT file
	robots = true
	
	## Donation Disable - Whether to turn off donation links
	noDono = true
	
	## Donation Links - Links to KoFi and Patreon
	kofi = ''
	patreon = ''
	
[menu]
	[[menu.main]]
		identifier = 'D. Travis Lee'
		url = '/'
		weight = 1
		[[menu.main.params]]
			disable=false
	[[menu.main]]
		identifier = 'tags'
		url = '/tags/'
		weight = 2
		[[menu.main.params]]
			disable=false
	[[menu.main]]
		identifier = 'contact'
		url = '/contact/'
		weight = 3
		[[menu.main.params]]
			disable=true
	[[menu.main]]
		identifier = 'about'
		url = '/about/'
		weight = 4
		[[menu.main.params]]
			disable=false
	[[menu.main]]
		identifier = 'donate'
		url = '/donate/'
		weight = 5
		[[menu.main.params]]
			disable=true
	[[menu.main]]
		identifier = 'rss'
		url = '/rss/'
		weight = 6
		[[menu.main.params]]
			disable=false
	[[menu.main]]
		identifier = 'search'
		url = '/search/'
		weight = 7
		[[menu.main.params]]
			class='js-only'
			disable=true
			
	
## Markup Settings
[markup]

	## Code Syntax Highlighting disable
	[markup.highlight]
		codeFences = false
		
	## Table of Contents Settings
	[markup.tableOfContents]
		ordered = true
		startLevel = 2
		endLevel = 6
	
	## Unsafe Markdown Toggle
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true